---
- hosts: teamcity
  user: vagrant
  sudo: yes
  vars:
    teamcity_user: teamcity
    teamcity_user_home: "/home/{{teamcity_user}}"
    install_dir: "{{teamcity_user_home}}"
    install_path: "{{install_dir}}/TeamCityAgent"
    data_path: "{{teamcity_user_home}}/TeamCityData"
    teamcity_url: http://localhost:8080
    teamcity_agent_name: linux agent

    sinopia_path: /home/vagrant
    local_user: vagrant
    sinopia_host: 8080
    sinopia_port: 8080

  roles:
    - base
    - teamcity
    - sinopia
