---
- name: create {{sinopia_path}} folder
  file: path={{sinopia_path}} state=directory recurse=true

- name: Install sinopia package globally.
  npm: name=sinopia global=yes path={{sinopia_path}}

- name: copy sinopia service init.d file
  sudo: yes
  template: src=sinopia.j2 dest=/etc/init.d/sinopia mode=755

- name: copy sinopia config.yaml
  template: src=config.yaml.j2 dest={{sinopia_path}}/config.yaml mode=755
  notify: restart sinopia

- name: start sinopia
  sudo: yes
  service: name=sinopia state=started enabled=yes
